<?php
/**
* @file
* A description of what your module does.
*/

//настрйока доступа к странице
function alfaq_db_permission() {
    return array(
        'alfaq db' => array(
            'title' => t('Alfaq db'),
            'description' => t('Perform administration tasks for my module.'),
        ),
    );
}


function alfaq_db_menu() {
    $items = array();
    $items['alfaq-db'] = array(
        'title' => 'Example bd',
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('alfaq_db_form'),
        'access arguments' => array('alfaq db'),
    );
    return $items;
}


function alfaq_db_form($form, &$form_state){
    $form['mynumber'] = array(
        '#type' => 'textfield',
        '#title' => t('My number'),
        '#size' => 10,
        '#maxlength' => 10,
        '#required' => TRUE,
        '#description' => t('Please enter number'),
    );
    $form['mytextfield'] = array(
        '#type' => 'textfield',
        '#title' => t('My textfield'),
        '#size' => 60,
        '#maxlength' => 255,
        '#required' => TRUE,
        '#description' => t('Please enter textfield'),
    );
    $form['mytext'] = array(
        '#type' => 'textarea',
        '#title' => t('My textarea'),
        '#required' => TRUE,
        '#default_value' => '',
        '#description' => t('Please enter some text'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Add item'),
    );
    return $form;
}

//валидац€ цифра или нет
function alfaq_db_form_validate($form, &$form_state){
    if(!is_numeric($form_state['values']['mynumber'])){
        form_set_error('mynumber', t('You cam enter a valid number'));
        return false;
    }
    return true;
}

//database Api
//вставка в Ѕƒ даных из формы
function alfaq_db_form_submit($form, &$form_state){
    $fe_id = db_insert('alfaq_db')
        ->fields(array(
            'mynumber' => $form_state['values']['mynumber'],
            'mytextfield' => $form_state['values']['mytextfield'],
            'mytext' => $form_state['values']['mytext'],
        ))
        ->execute();

    drupal_set_message(t('Your form entry has been added'));

}